sudo: true
language: python
python: 
  - 3.6
  - nightly

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

install:
  - pip install -r requirements/dev.txt

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - sudo chmod +x $PWD/geckodriver/geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - nosetests --with-cov --cov-config .coveragerc
after_success:
  - codecov
jobs:
  include:
    - stage: Deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: jgA88sgpIxyGW7sgNsXXiCsL16pttQzoTZio5vmGKZiXGaNqp24iDLP34KO4Y/D52A83iWBIRb/qhX0QDBAg6bWqzZHHPoUtTuFCT18/1OqjnBTw++uLvwOcncHuqYE/EKvwZCwRXe5UbmLfkzd67N3QOGTrzf5mkVM6tfKfPl3GDvY5zcKxczi1RRA/4SswvEtLlfey/ZzjMEjxMYt0NvlQU1Ll3mmzfkbJeFKjjOeJLhsxPOjZtErd7TPxYctG7w22Io1JqbOTiG9PDCheu5Ax+W53C7/aalLXbqFDNdFhwhFZDXp9yyuDwJGgnQQq13X/6XAG+GFvLxEqUz4JxCs/hJ6rkbmxgZqGyvWQ+aKJYe4Lj4tR5W1gRv5CxB30w7/2OkfkHeM0MDS4JqXUg3nplGjNqm9ZmkghngNJVmMIpdenN/o30CFBBR1tKQSprBo64SErHvs8l4tberW96Df3cBEykTXzoQiu0KRlg1FEufk0CCK/iZdKGTDJO8T6CKGXLzmC+ixW+3nowWZjhfp+x4ynYE4grn6m+rY2ACYBS97xiObKbu6fn5FPqIPyhCFSlUCJ6nbumunxer20LWB1nj0pykxpLd0uG2dzL7Yu2WC3IGqCCewdVj4H4pRJ/Ou+As4vn/+6sI6maBt/dMf3zM6fXke6TUiFsZRV5UY=
        app: barko-ci-amsterdam
        on:
          repo: wimvanp1/ci_workshop