sudo: true
language: python
python: 
  - 3.6
  - nightly

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

install:
  - pip install -r requirements/dev.txt

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - sudo chmod +x $PWD/geckodriver/geckodriver
  - export PATH=$PATH:$PWD/geckodriver

script:
  - nosetests --with-cov --cov-config .coveragerc
after_success:
  - codecov
jobs:
  include:
    - stage: Deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: iwCN2plvdmJkJLsbKwbHr+gUapdJVikgRPvN0/56CdmJt/iAS1zW9KRutO2LTD2LcVZJHBBz6U9+jgR69iwJj4V5xekyqhnboyMrn8GLGziqDs5fKwzLVR6EfFexXdFbtlismhY2AlwoM1Hy7OCU/uTdK3fPEnj98Q7cuSu8ttro0Z+IU522nfgIwZh0vQsuS8uff7D5sbXhBpPHJW6V3h494Dl5pCOVtvrHM/B06/nqmyb708ulkL5BS0ZRF70XSDYWA+UbH+qissG+lIx4zx8Yy/KF6fCCB65eyZsyBjwbp0cCntuTCBWN994wHU0hm93CvodGenhuSS0qjvrraFSCMq6AUb2BelVpUXihe+hcFqRvevPYkg3jArFwhPl97nZ8rWTNHTSdMi+DdBZmDGSTHiimpMzhTu5WKinGMA6zVY2sj13kQiIDGJFZmsctCgPk6x0RB5CU5qbo5SCF9qsQ8XMHmSyfzS5XNYKkjVd+KozHLGfwrVLlpX9vA6POalkcxoXgEzvB56f08vLX7RjJ0eEWXGIOEJceI92M3/s1eXsqrMZveIH4BZcwBH7WKGzN+9ioXOBdaY4jyvc0RYnXq4NfEJIDrjxQ7/qSCqSX3//LLFrPs0F0KzIAEg6UiDCPvdaWV4THXCqI+bPwt8AcNqfXRSrz8Um9CJescdg=
        app: barko-ci-amsterdam
        on:
          repo: wimvanp1/ci_workshop